---

inventory_sources:
  - name: "{{ groups['sat_primary'][0] }}"
    credential: "prod_satellite"
    description: "production satellite inventory source"
    execution_environment: "satellite_ee"
    inventory: "{{ groups['sat_primary'][0] }}"
    organization: "Default"
    overwrite: true
    source: "satellite6"
    source_vars:
      batch_size: 500
      use_extra_vars: true
      want_facts: true
      want_params: true
    state: "present"
    update_on_launch: true
