---
# Add the manifest from the CDN to the controller

# API Broken??

- name: "Upload the manifest to the Controller"
  when:
    - platform_deployment_type == "rpm"
  ansible.controller.license:
    controller_host: "{{ groups['aap_controllers'][0] }}"
    controller_username: "{{ platform_installer_config.aap_platform_username }}"
    controller_password: "{{ platform_installer_config.aap_platform_password }}"
    manifest: "{{ redhat_manifest.path }}"
    force: true
    state: "present"
    validate_certs: "false"
