---
# add a list of credentials to aap

- name: "Add the list of credentials to the Controller"
  ansible.builtin.include_tasks: "ensure_aap_credential_type.yml"
  loop: "{{ aap_credential_types }}"
  loop_control:
    loop_var: credential_type
  no_log: true
